"""
MAVLink protocol implementation (auto-generated by mavgen.py)

Generated from: ('ihm_dialect.xml',)

Note: this file has been auto-generated. DO NOT EDIT
"""
import hashlib
import json
import logging
import os
import struct
import sys
import time
from builtins import object, range
from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Type, Union

WIRE_PROTOCOL_VERSION = "2.0"
DIALECT = "ihm_dialect"

PROTOCOL_MARKER_V1 = 0xFE
PROTOCOL_MARKER_V2 = 0xFD
HEADER_LEN_V1 = 6
HEADER_LEN_V2 = 10

MAVLINK_SIGNATURE_BLOCK_LEN = 13

MAVLINK_IFLAG_SIGNED = 0x01

logger = logging.getLogger(__name__)

# allow MAV_IGNORE_CRC=1 to ignore CRC, allowing some
# corrupted msgs to be seen
MAVLINK_IGNORE_CRC = os.environ.get("MAV_IGNORE_CRC", 0)

# some base types from mavlink_types.h
MAVLINK_TYPE_CHAR = 0
MAVLINK_TYPE_UINT8_T = 1
MAVLINK_TYPE_INT8_T = 2
MAVLINK_TYPE_UINT16_T = 3
MAVLINK_TYPE_INT16_T = 4
MAVLINK_TYPE_UINT32_T = 5
MAVLINK_TYPE_INT32_T = 6
MAVLINK_TYPE_UINT64_T = 7
MAVLINK_TYPE_INT64_T = 8
MAVLINK_TYPE_FLOAT = 9
MAVLINK_TYPE_DOUBLE = 10

# CRC calculation using fastcrc, falling back to a pure Python implementation
# if fastcrc is not available
try:
    import fastcrc
    mcrf4xx = fastcrc.crc16.mcrf4xx
except Exception:
    mcrf4xx = None  # type: ignore


BytesLike = Union[List[int], Tuple[int], bytes, bytearray, str]


class _x25crc_slow(object):
    """CRC-16/MCRF4XX - based on checksum.h from mavlink library"""

    crc: int

    def __init__(self, buf: Optional[BytesLike] = None):
        self.crc = 0xFFFF
        if buf is not None:
            self.accumulate(buf)

    def accumulate(self, buf: BytesLike) -> None:
        """add in some more bytes (it also accepts strings)"""
        if isinstance(buf, str):
            buf = buf.encode()

        accum = self.crc
        for b in buf:
            tmp = b ^ (accum & 0xFF)
            tmp = (tmp ^ (tmp << 4)) & 0xFF
            accum = (accum >> 8) ^ (tmp << 8) ^ (tmp << 3) ^ (tmp >> 4)
        self.crc = accum


class _x25crc_fast(object):
    """CRC-16/MCRF4XX - based on checksum.h from mavlink library"""

    def __init__(self, buf: Optional[BytesLike] = None):
        self.crc = 0xFFFF
        if buf is not None:
            self.accumulate(buf)

    def accumulate(self, buf: BytesLike) -> None:
        """add in some more bytes (it also accepts strings)"""
        if isinstance(buf, str):
            buf_as_bytes = bytes(buf.encode())
        elif isinstance(buf, (list, tuple, bytearray)):
            buf_as_bytes = bytes(buf)
        else:
            buf_as_bytes = buf
        self.crc = mcrf4xx(buf_as_bytes, self.crc)


x25crc = _x25crc_fast if mcrf4xx is not None else _x25crc_slow


class MAVLink_header(object):
    """MAVLink message header"""

    def __init__(self, msgId: int, incompat_flags: int = 0, compat_flags: int = 0, mlen: int = 0, seq: int = 0, srcSystem: int = 0, srcComponent: int = 0) -> None:
        self.mlen = mlen
        self.seq = seq
        self.srcSystem = srcSystem
        self.srcComponent = srcComponent
        self.msgId = msgId
        self.incompat_flags = incompat_flags
        self.compat_flags = compat_flags

    def pack(self, force_mavlink1: bool = False) -> bytes:
        if float(WIRE_PROTOCOL_VERSION) == 2.0 and not force_mavlink1:
            return struct.pack(
                "<BBBBBBBHB",
                253,
                self.mlen,
                self.incompat_flags,
                self.compat_flags,
                self.seq,
                self.srcSystem,
                self.srcComponent,
                self.msgId & 0xFFFF,
                self.msgId >> 16,
            )
        return struct.pack(
            "<BBBBBB",
            PROTOCOL_MARKER_V1,
            self.mlen,
            self.seq,
            self.srcSystem,
            self.srcComponent,
            self.msgId,
        )


class MAVLink_message(object):
    """base MAVLink message class"""

    id = 0
    msgname = ""
    fieldnames: List[str] = []
    ordered_fieldnames: List[str] = []
    fieldtypes: List[str] = []
    fielddisplays_by_name: Dict[str, str] = {}
    fieldenums_by_name: Dict[str, str] = {}
    fieldunits_by_name: Dict[str, str] = {}
    native_format = bytearray(b"")
    orders: List[int] = []
    lengths: List[int] = []
    array_lengths: List[int] = []
    crc_extra = 0
    unpacker = struct.Struct("")
    instance_field: Optional[str] = None
    instance_offset = -1

    def __init__(self, msgId: int, name: str) -> None:
        self._header = MAVLink_header(msgId)
        self._payload: Optional[bytes] = None
        self._msgbuf = bytearray(b"")
        self._crc: Optional[int] = None
        self._fieldnames: List[str] = []
        self._type = name
        self._signed = False
        self._link_id: Optional[int] = None
        self._instances: Optional[Dict[str, str]] = None
        self._instance_field: Optional[str] = None

    def format_attr(self, field: str) -> Union[str, float, int]:
        """override field getter"""
        raw_attr: Union[bytes, float, int] = getattr(self, field)
        if isinstance(raw_attr, bytes):
            return raw_attr.decode(errors="backslashreplace").rstrip("\x00")
        return raw_attr

    def get_msgbuf(self) -> bytearray:
        return self._msgbuf

    def get_header(self) -> MAVLink_header:
        return self._header

    def get_payload(self) -> Optional[bytes]:
        return self._payload

    def get_crc(self) -> Optional[int]:
        return self._crc

    def get_fieldnames(self) -> List[str]:
        return self._fieldnames

    def get_type(self) -> str:
        return self._type

    def get_msgId(self) -> int:
        return self._header.msgId

    def get_srcSystem(self) -> int:
        return self._header.srcSystem

    def get_srcComponent(self) -> int:
        return self._header.srcComponent

    def get_seq(self) -> int:
        return self._header.seq

    def get_signed(self) -> bool:
        return self._signed

    def get_link_id(self) -> Optional[int]:
        return self._link_id

    def __str__(self) -> str:
        ret = "%s {" % self._type
        for a in self._fieldnames:
            v = self.format_attr(a)
            ret += "%s : %s, " % (a, v)
        ret = ret[0:-2] + "}"
        return ret

    def __ne__(self, other: object) -> bool:
        return not self.__eq__(other)

    def __eq__(self, other: object) -> bool:
        if other is None:
            return False

        if not isinstance(other, MAVLink_message):
            return False

        if self.get_type() != other.get_type():
            return False

        if self.get_crc() != other.get_crc():
            return False

        if self.get_seq() != other.get_seq():
            return False

        if self.get_srcSystem() != other.get_srcSystem():
            return False

        if self.get_srcComponent() != other.get_srcComponent():
            return False

        for a in self._fieldnames:
            if self.format_attr(a) != other.format_attr(a):
                return False

        return True

    def to_dict(self) -> Dict[str, Union[str, float, int]]:
        d: Dict[str, Union[str, float, int]] = {}
        d["mavpackettype"] = self._type
        for a in self._fieldnames:
            d[a] = self.format_attr(a)
        return d

    def to_json(self) -> str:
        return json.dumps(self.to_dict())

    def sign_packet(self, mav: "MAVLink") -> None:
        assert mav.signing.secret_key is not None

        h = hashlib.new("sha256")
        self._msgbuf += struct.pack("<BQ", mav.signing.link_id, mav.signing.timestamp)[:7]
        h.update(mav.signing.secret_key)
        h.update(self._msgbuf)
        sig = h.digest()[:6]
        self._msgbuf += sig
        mav.signing.timestamp += 1

    def _pack(self, mav: "MAVLink", crc_extra: int, payload: bytes, force_mavlink1: bool = False) -> bytes:
        plen = len(payload)
        if float(WIRE_PROTOCOL_VERSION) == 2.0 and not force_mavlink1:
            # in MAVLink2 we can strip trailing zeros off payloads. This allows for simple
            # variable length arrays and smaller packets
            nullbyte = 0
            while plen > 1 and payload[plen - 1] == nullbyte:
                plen -= 1
        self._payload = payload[:plen]
        incompat_flags = 0
        if mav.signing.sign_outgoing:
            incompat_flags |= MAVLINK_IFLAG_SIGNED
        self._header = MAVLink_header(
            self._header.msgId,
            incompat_flags=incompat_flags,
            compat_flags=0,
            mlen=len(self._payload),
            seq=mav.seq,
            srcSystem=mav.srcSystem,
            srcComponent=mav.srcComponent,
        )
        self._msgbuf = bytearray(self._header.pack(force_mavlink1=force_mavlink1))
        self._msgbuf += self._payload
        crc = x25crc(self._msgbuf[1:])
        if True:
            # we are using CRC extra
            crc.accumulate(struct.pack("B", crc_extra))
        self._crc = crc.crc
        self._msgbuf += struct.pack("<H", self._crc)
        if mav.signing.sign_outgoing and not force_mavlink1:
            self.sign_packet(mav)
        return bytes(self._msgbuf)

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        raise NotImplementedError("MAVLink_message cannot be serialized directly")

    def __getitem__(self, key: str) -> str:
        """support indexing, allowing for multi-instance sensors in one message"""
        if self._instances is None:
            raise IndexError()
        if key not in self._instances:
            raise IndexError()
        return self._instances[key]


class mavlink_msg_deprecated_name_property(object):
    """
    This handles the class variable name change from name to msgname for
    subclasses of MAVLink_message during a transition period.

    This is used by setting the class variable to
    `mavlink_msg_deprecated_name_property()`.
    """

    def __get__(self, instance: Optional[MAVLink_message], owner: Type[MAVLink_message]) -> str:
        if instance is not None:
            logger.error("Using .name on a MAVLink_message is not supported, use .get_type() instead.")
            raise AttributeError("Class {} has no attribute 'name'".format(owner.__name__))
        logger.warning(
            """Using .name on a MAVLink_message class is deprecated, consider using .msgname instead.
Note that if compatibility with pymavlink 2.4.30 and earlier is desired, use something like this:

msg_name =  msg.msgname if hasattr(msg, "msgname") else msg.name"""
        )
        return owner.msgname


# enums


class EnumEntry(object):
    def __init__(self, name: str, description: str) -> None:
        self.name = name
        self.description = description
        self.param: Dict[int, str] = {}
        self.has_location = False

class Enum(Dict[int, EnumEntry]):
    def __init__(self) -> None:
        self.bitmask = False

enums: Dict[str, Enum] = {}

# IHM_ENCODER_DIRECTION
enums["IHM_ENCODER_DIRECTION"] = Enum()
enums["IHM_ENCODER_DIRECTION"].bitmask = False
IHM_ENCODER_NOT_SUPPORTED = 0
enums["IHM_ENCODER_DIRECTION"][0] = EnumEntry(
    "IHM_ENCODER_NOT_SUPPORTED",
    """
          No movement since this encoder was last read (RotaryEncoder::
          getDirection() resets to this value after every read, so this
          also just means "nothing new since the last sample").
        """,
)
IHM_ENCODER_CCW = 1
enums["IHM_ENCODER_DIRECTION"][1] = EnumEntry("IHM_ENCODER_CCW", """Counter-clockwise movement.""")
IHM_ENCODER_CW = 2
enums["IHM_ENCODER_DIRECTION"][2] = EnumEntry("IHM_ENCODER_CW", """Clockwise movement.""")
IHM_ENCODER_DIRECTION_ENUM_END = 3
enums["IHM_ENCODER_DIRECTION"][3] = EnumEntry("IHM_ENCODER_DIRECTION_ENUM_END", """""")

# PWM_FREQUENCY
enums["PWM_FREQUENCY"] = Enum()
enums["PWM_FREQUENCY"].bitmask = False
PWM_FREQUENCY_62500_HZ = 0
enums["PWM_FREQUENCY"][0] = EnumEntry("PWM_FREQUENCY_62500_HZ", """frequency_62_500HZ.""")
PWM_FREQUENCY_31250_HZ = 1
enums["PWM_FREQUENCY"][1] = EnumEntry("PWM_FREQUENCY_31250_HZ", """frequency_31_250HZ.""")
PWM_FREQUENCY_15625_HZ = 2
enums["PWM_FREQUENCY"][2] = EnumEntry("PWM_FREQUENCY_15625_HZ", """frequency_15_625HZ.""")
PWM_FREQUENCY_7812_HZ = 3
enums["PWM_FREQUENCY"][3] = EnumEntry("PWM_FREQUENCY_7812_HZ", """frequency_7812_5HZ.""")
PWM_FREQUENCY_3906_HZ = 4
enums["PWM_FREQUENCY"][4] = EnumEntry("PWM_FREQUENCY_3906_HZ", """frequency_3906_25HZ.""")
PWM_FREQUENCY_1953_HZ = 5
enums["PWM_FREQUENCY"][5] = EnumEntry("PWM_FREQUENCY_1953_HZ", """frequency_1953_125HZ.""")
PWM_FREQUENCY_976_HZ = 6
enums["PWM_FREQUENCY"][6] = EnumEntry("PWM_FREQUENCY_976_HZ", """frequency_976_5625HZ.""")
PWM_FREQUENCY_488_HZ = 7
enums["PWM_FREQUENCY"][7] = EnumEntry("PWM_FREQUENCY_488_HZ", """frequency_488_28125HZ.""")
PWM_FREQUENCY_244_HZ = 8
enums["PWM_FREQUENCY"][8] = EnumEntry("PWM_FREQUENCY_244_HZ", """frequency_244_140625HZ.""")
PWM_FREQUENCY_122_HZ = 9
enums["PWM_FREQUENCY"][9] = EnumEntry("PWM_FREQUENCY_122_HZ", """frequency_122_0703125HZ.""")
PWM_FREQUENCY_61_HZ = 10
enums["PWM_FREQUENCY"][10] = EnumEntry("PWM_FREQUENCY_61_HZ", """frequency_61_03515625HZ.""")
PWM_FREQUENCY_30_HZ = 11
enums["PWM_FREQUENCY"][11] = EnumEntry("PWM_FREQUENCY_30_HZ", """frequency_30_517578125HZ.""")
PWM_FREQUENCY_15_HZ = 12
enums["PWM_FREQUENCY"][12] = EnumEntry("PWM_FREQUENCY_15_HZ", """frequency_15_2587890625HZ.""")
PWM_FREQUENCY_VARIABLE = 13
enums["PWM_FREQUENCY"][13] = EnumEntry(
    "PWM_FREQUENCY_VARIABLE",
    """
          frequency_variable -- Fast PWM mode 14, TOP = ICRn. The
          PWM_CHANNEL_CONFIG.frequency field supplies that raw TOP; it is
          ignored for every other selector.
        """,
)
PWM_FREQUENCY_ENUM_END = 14
enums["PWM_FREQUENCY"][14] = EnumEntry("PWM_FREQUENCY_ENUM_END", """""")

# message IDs
MAVLINK_MSG_ID_BAD_DATA = -1
MAVLINK_MSG_ID_UNKNOWN = -2
MAVLINK_MSG_ID_IHM_BOARD_STATE = 300
MAVLINK_MSG_ID_CAN_SIGNAL_CONFIG = 301
MAVLINK_MSG_ID_RS485_SIGNAL_CONFIG = 302
MAVLINK_MSG_ID_PWM_CHANNEL_CONFIG = 303
MAVLINK_MSG_ID_IHM_RELAY_STATE = 304
MAVLINK_MSG_ID_IHM_SIMULATE_ENCODER = 305


class MAVLink_ihm_board_state_message(MAVLink_message):
    """
    Periodic/on-change snapshot of the board's user-input state,
    analog         inputs, and loop-timing debug info. Board -> PC,
    telemetry.          Field widths are intentionally not bit-packed
    across byte boundaries         (e.g. each encoder gets its own
    byte rather than 3 encoders sharing         9 bits): with
    MAVLINK_MAX_PAYLOAD_LEN raised to 64 for future         headroom,
    the few bytes saved by tight packing weren't worth the
    hand-rolled bit-shift/mask code on both the firmware and PC sides.
    This message is 19 bytes either way, well under the cap.
    """

    id = MAVLINK_MSG_ID_IHM_BOARD_STATE
    msgname = "IHM_BOARD_STATE"
    fieldnames = ["buttons", "encoder0_direction", "encoder1_direction", "encoder2_direction", "rotation", "charging", "batt_voltage", "analog_in", "time_statistics", "time_counter"]
    ordered_fieldnames = ["batt_voltage", "analog_in", "time_statistics", "buttons", "encoder0_direction", "encoder1_direction", "encoder2_direction", "rotation", "charging", "time_counter"]
    fieldtypes = ["uint8_t", "uint8_t", "uint8_t", "uint8_t", "uint8_t", "uint8_t", "uint16_t", "uint16_t", "uint16_t", "uint8_t"]
    fielddisplays_by_name: Dict[str, str] = {}
    fieldenums_by_name: Dict[str, str] = {"encoder0_direction": "IHM_ENCODER_DIRECTION", "encoder1_direction": "IHM_ENCODER_DIRECTION", "encoder2_direction": "IHM_ENCODER_DIRECTION"}
    fieldunits_by_name: Dict[str, str] = {}
    native_format = bytearray(b"<HHHBBBBBBB")
    orders = [3, 4, 5, 6, 7, 8, 0, 1, 2, 9]
    lengths = [1, 4, 1, 1, 1, 1, 1, 1, 1, 1]
    array_lengths = [0, 4, 0, 0, 0, 0, 0, 0, 0, 0]
    crc_extra = 157
    unpacker = struct.Struct("<H4HHBBBBBBB")
    instance_field = None
    instance_offset = -1

    def __init__(self, buttons: int, encoder0_direction: int, encoder1_direction: int, encoder2_direction: int, rotation: int, charging: int, batt_voltage: int, analog_in: Sequence[int], time_statistics: int, time_counter: int):
        MAVLink_message.__init__(self, MAVLink_ihm_board_state_message.id, MAVLink_ihm_board_state_message.msgname)
        self._fieldnames = MAVLink_ihm_board_state_message.fieldnames
        self._instance_field = MAVLink_ihm_board_state_message.instance_field
        self._instance_offset = MAVLink_ihm_board_state_message.instance_offset
        self.buttons = buttons
        self.encoder0_direction = encoder0_direction
        self.encoder1_direction = encoder1_direction
        self.encoder2_direction = encoder2_direction
        self.rotation = rotation
        self.charging = charging
        self.batt_voltage = batt_voltage
        self.analog_in = analog_in
        self.time_statistics = time_statistics
        self.time_counter = time_counter

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.batt_voltage, self.analog_in[0], self.analog_in[1], self.analog_in[2], self.analog_in[3], self.time_statistics, self.buttons, self.encoder0_direction, self.encoder1_direction, self.encoder2_direction, self.rotation, self.charging, self.time_counter), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_ihm_board_state_message, "name", mavlink_msg_deprecated_name_property())


class MAVLink_can_signal_config_message(MAVLink_message):
    """
    Configure/start/stop a generated signal on one of the board's 2
    CAN         buses. One active signal per bus -- sending a new
    config for a         bus_id replaces whatever was previously
    configured there. The board         transmits exactly the given
    bytes on a schedule; no waveform math         happens on-board. PC
    -> board, command.
    """

    id = MAVLINK_MSG_ID_CAN_SIGNAL_CONFIG
    msgname = "CAN_SIGNAL_CONFIG"
    fieldnames = ["bus_id", "can_id", "extended_id", "dlc", "data", "period_ms", "repeat_count", "enable"]
    ordered_fieldnames = ["can_id", "period_ms", "repeat_count", "bus_id", "extended_id", "dlc", "data", "enable"]
    fieldtypes = ["uint8_t", "uint32_t", "uint8_t", "uint8_t", "uint8_t", "uint16_t", "uint16_t", "uint8_t"]
    fielddisplays_by_name: Dict[str, str] = {}
    fieldenums_by_name: Dict[str, str] = {}
    fieldunits_by_name: Dict[str, str] = {}
    native_format = bytearray(b"<IHHBBBBB")
    orders = [3, 0, 4, 5, 6, 1, 2, 7]
    lengths = [1, 1, 1, 1, 1, 1, 8, 1]
    array_lengths = [0, 0, 0, 0, 0, 0, 8, 0]
    crc_extra = 176
    unpacker = struct.Struct("<IHHBBB8BB")
    instance_field = None
    instance_offset = -1

    def __init__(self, bus_id: int, can_id: int, extended_id: int, dlc: int, data: Sequence[int], period_ms: int, repeat_count: int, enable: int):
        MAVLink_message.__init__(self, MAVLink_can_signal_config_message.id, MAVLink_can_signal_config_message.msgname)
        self._fieldnames = MAVLink_can_signal_config_message.fieldnames
        self._instance_field = MAVLink_can_signal_config_message.instance_field
        self._instance_offset = MAVLink_can_signal_config_message.instance_offset
        self.bus_id = bus_id
        self.can_id = can_id
        self.extended_id = extended_id
        self.dlc = dlc
        self.data = data
        self.period_ms = period_ms
        self.repeat_count = repeat_count
        self.enable = enable

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.can_id, self.period_ms, self.repeat_count, self.bus_id, self.extended_id, self.dlc, self.data[0], self.data[1], self.data[2], self.data[3], self.data[4], self.data[5], self.data[6], self.data[7], self.enable), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_can_signal_config_message, "name", mavlink_msg_deprecated_name_property())


class MAVLink_rs485_signal_config_message(MAVLink_message):
    """
    Configure/start/stop a generated signal on the board's RS-485
    connection. One active signal at a time -- a new config replaces
    whatever was previously running. Raw byte transmission, no framing
    imposed (no protocol defined over this link yet). PC -> board,
    command.
    """

    id = MAVLINK_MSG_ID_RS485_SIGNAL_CONFIG
    msgname = "RS485_SIGNAL_CONFIG"
    fieldnames = ["length", "data", "period_ms", "repeat_count", "enable"]
    ordered_fieldnames = ["period_ms", "repeat_count", "length", "data", "enable"]
    fieldtypes = ["uint8_t", "uint8_t", "uint16_t", "uint16_t", "uint8_t"]
    fielddisplays_by_name: Dict[str, str] = {}
    fieldenums_by_name: Dict[str, str] = {}
    fieldunits_by_name: Dict[str, str] = {}
    native_format = bytearray(b"<HHBBB")
    orders = [2, 3, 0, 1, 4]
    lengths = [1, 1, 1, 32, 1]
    array_lengths = [0, 0, 0, 32, 0]
    crc_extra = 161
    unpacker = struct.Struct("<HHB32BB")
    instance_field = None
    instance_offset = -1

    def __init__(self, length: int, data: Sequence[int], period_ms: int, repeat_count: int, enable: int):
        MAVLink_message.__init__(self, MAVLink_rs485_signal_config_message.id, MAVLink_rs485_signal_config_message.msgname)
        self._fieldnames = MAVLink_rs485_signal_config_message.fieldnames
        self._instance_field = MAVLink_rs485_signal_config_message.instance_field
        self._instance_offset = MAVLink_rs485_signal_config_message.instance_offset
        self.length = length
        self.data = data
        self.period_ms = period_ms
        self.repeat_count = repeat_count
        self.enable = enable

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.period_ms, self.repeat_count, self.length, self.data[0], self.data[1], self.data[2], self.data[3], self.data[4], self.data[5], self.data[6], self.data[7], self.data[8], self.data[9], self.data[10], self.data[11], self.data[12], self.data[13], self.data[14], self.data[15], self.data[16], self.data[17], self.data[18], self.data[19], self.data[20], self.data[21], self.data[22], self.data[23], self.data[24], self.data[25], self.data[26], self.data[27], self.data[28], self.data[29], self.data[30], self.data[31], self.enable), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_rs485_signal_config_message, "name", mavlink_msg_deprecated_name_property())


class MAVLink_pwm_channel_config_message(MAVLink_message):
    """
    Configure one of the board's 4 PWM channels. PC -> board, command.
    The board applies it to the timer registers immediately; there is
    no ack. Sending a new config for a channel replaces its previous
    one (last writer wins, including against the on-screen PWM tab,
    which drives the same registers).          One message shape
    covers both channel kinds (see
    IHM/lib/MultiOutput/src/PWM.h):           * channels 0 and 1 are
    "simplex" -- a single output (OC3A /             OC5A). Only
    out1_* is used; out2_* and out3_* are ignored.           *
    channels 2 and 3 are "complex" -- three independent outputs
    A/B/C (OC1A/B/C, OC4A/B/C). out1_/out2_/out3_ map to A/B/C.
    Same "not bit-packed across byte boundaries" convention as the
    other messages here -- each flag gets its own byte. 13 bytes,
    well under the 64-byte cap.
    """

    id = MAVLINK_MSG_ID_PWM_CHANNEL_CONFIG
    msgname = "PWM_CHANNEL_CONFIG"
    fieldnames = ["channel", "f_selector", "frequency", "out1_enabled", "out1_inverting", "out1_duty_percent", "out2_enabled", "out2_inverting", "out2_duty_percent", "out3_enabled", "out3_inverting", "out3_duty_percent"]
    ordered_fieldnames = ["frequency", "channel", "f_selector", "out1_enabled", "out1_inverting", "out1_duty_percent", "out2_enabled", "out2_inverting", "out2_duty_percent", "out3_enabled", "out3_inverting", "out3_duty_percent"]
    fieldtypes = ["uint8_t", "uint8_t", "uint16_t", "uint8_t", "uint8_t", "uint8_t", "uint8_t", "uint8_t", "uint8_t", "uint8_t", "uint8_t", "uint8_t"]
    fielddisplays_by_name: Dict[str, str] = {}
    fieldenums_by_name: Dict[str, str] = {"f_selector": "PWM_FREQUENCY"}
    fieldunits_by_name: Dict[str, str] = {}
    native_format = bytearray(b"<HBBBBBBBBBBB")
    orders = [1, 2, 0, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    lengths = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    array_lengths = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    crc_extra = 93
    unpacker = struct.Struct("<HBBBBBBBBBBB")
    instance_field = None
    instance_offset = -1

    def __init__(self, channel: int, f_selector: int, frequency: int, out1_enabled: int, out1_inverting: int, out1_duty_percent: int, out2_enabled: int, out2_inverting: int, out2_duty_percent: int, out3_enabled: int, out3_inverting: int, out3_duty_percent: int):
        MAVLink_message.__init__(self, MAVLink_pwm_channel_config_message.id, MAVLink_pwm_channel_config_message.msgname)
        self._fieldnames = MAVLink_pwm_channel_config_message.fieldnames
        self._instance_field = MAVLink_pwm_channel_config_message.instance_field
        self._instance_offset = MAVLink_pwm_channel_config_message.instance_offset
        self.channel = channel
        self.f_selector = f_selector
        self.frequency = frequency
        self.out1_enabled = out1_enabled
        self.out1_inverting = out1_inverting
        self.out1_duty_percent = out1_duty_percent
        self.out2_enabled = out2_enabled
        self.out2_inverting = out2_inverting
        self.out2_duty_percent = out2_duty_percent
        self.out3_enabled = out3_enabled
        self.out3_inverting = out3_inverting
        self.out3_duty_percent = out3_duty_percent

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.frequency, self.channel, self.f_selector, self.out1_enabled, self.out1_inverting, self.out1_duty_percent, self.out2_enabled, self.out2_inverting, self.out2_duty_percent, self.out3_enabled, self.out3_inverting, self.out3_duty_percent), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_pwm_channel_config_message, "name", mavlink_msg_deprecated_name_property())


class MAVLink_ihm_relay_state_message(MAVLink_message):
    """
    Periodic snapshot of all 8 relay outputs. Board -> PC, telemetry,
    read-only -- there is no PC -> board relay command yet (relays are
    only toggled locally, by the physical buttons or the on-screen
    Relay tab). Mirrors main.cpp's relayState[NUMBER_OF_RELAYS] the
    same way IHM_BOARD_STATE.buttons mirrors the button bitmap.
    """

    id = MAVLINK_MSG_ID_IHM_RELAY_STATE
    msgname = "IHM_RELAY_STATE"
    fieldnames = ["relays"]
    ordered_fieldnames = ["relays"]
    fieldtypes = ["uint8_t"]
    fielddisplays_by_name: Dict[str, str] = {}
    fieldenums_by_name: Dict[str, str] = {}
    fieldunits_by_name: Dict[str, str] = {}
    native_format = bytearray(b"<B")
    orders = [0]
    lengths = [1]
    array_lengths = [0]
    crc_extra = 163
    unpacker = struct.Struct("<B")
    instance_field = None
    instance_offset = -1

    def __init__(self, relays: int):
        MAVLink_message.__init__(self, MAVLink_ihm_relay_state_message.id, MAVLink_ihm_relay_state_message.msgname)
        self._fieldnames = MAVLink_ihm_relay_state_message.fieldnames
        self._instance_field = MAVLink_ihm_relay_state_message.instance_field
        self._instance_offset = MAVLink_ihm_relay_state_message.instance_offset
        self.relays = relays

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.relays), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_ihm_relay_state_message, "name", mavlink_msg_deprecated_name_property())


class MAVLink_ihm_simulate_encoder_message(MAVLink_message):
    """
    PC injects one simulated rotation step on the given encoder. The
    board applies it only if that encoder's real hardware read was
    idle (not_supported) on the same superloop pass -- real input
    always wins, no fight between the two sources. Consumed exactly
    once, mirroring the real encoder's own edge-triggered/consumed-
    on-read semantics (RotaryEncoder.h). No ack. PC -> board, command.
    """

    id = MAVLINK_MSG_ID_IHM_SIMULATE_ENCODER
    msgname = "IHM_SIMULATE_ENCODER"
    fieldnames = ["encoder", "direction"]
    ordered_fieldnames = ["encoder", "direction"]
    fieldtypes = ["uint8_t", "uint8_t"]
    fielddisplays_by_name: Dict[str, str] = {}
    fieldenums_by_name: Dict[str, str] = {"direction": "IHM_ENCODER_DIRECTION"}
    fieldunits_by_name: Dict[str, str] = {}
    native_format = bytearray(b"<BB")
    orders = [0, 1]
    lengths = [1, 1]
    array_lengths = [0, 0]
    crc_extra = 19
    unpacker = struct.Struct("<BB")
    instance_field = None
    instance_offset = -1

    def __init__(self, encoder: int, direction: int):
        MAVLink_message.__init__(self, MAVLink_ihm_simulate_encoder_message.id, MAVLink_ihm_simulate_encoder_message.msgname)
        self._fieldnames = MAVLink_ihm_simulate_encoder_message.fieldnames
        self._instance_field = MAVLink_ihm_simulate_encoder_message.instance_field
        self._instance_offset = MAVLink_ihm_simulate_encoder_message.instance_offset
        self.encoder = encoder
        self.direction = direction

    def pack(self, mav: "MAVLink", force_mavlink1: bool = False) -> bytes:
        return self._pack(mav, self.crc_extra, self.unpacker.pack(self.encoder, self.direction), force_mavlink1=force_mavlink1)


# Define name on the class for backwards compatibility (it is now msgname).
# Done with setattr to hide the class variable from mypy.
setattr(MAVLink_ihm_simulate_encoder_message, "name", mavlink_msg_deprecated_name_property())


mavlink_map: Dict[int, Type[MAVLink_message]] = {
    MAVLINK_MSG_ID_IHM_BOARD_STATE: MAVLink_ihm_board_state_message,
    MAVLINK_MSG_ID_CAN_SIGNAL_CONFIG: MAVLink_can_signal_config_message,
    MAVLINK_MSG_ID_RS485_SIGNAL_CONFIG: MAVLink_rs485_signal_config_message,
    MAVLINK_MSG_ID_PWM_CHANNEL_CONFIG: MAVLink_pwm_channel_config_message,
    MAVLINK_MSG_ID_IHM_RELAY_STATE: MAVLink_ihm_relay_state_message,
    MAVLINK_MSG_ID_IHM_SIMULATE_ENCODER: MAVLink_ihm_simulate_encoder_message,
}


class MAVError(Exception):
    """MAVLink error class"""

    def __init__(self, msg: str) -> None:
        Exception.__init__(self, msg)
        self.message = msg


class MAVLink_bad_data(MAVLink_message):
    """
    a piece of bad data in a mavlink stream
    """

    def __init__(self, data: bytes, reason: str) -> None:
        MAVLink_message.__init__(self, MAVLINK_MSG_ID_BAD_DATA, "BAD_DATA")
        self._fieldnames = ["data", "reason"]
        self.data = data
        self.reason = reason
        self._msgbuf = bytearray(data)
        self._instance_field = None

    def __str__(self) -> str:
        """Override the __str__ function from MAVLink_messages because non-printable characters are common in to be the reason for this message to exist."""
        hexstr = ["{:x}".format(i) for i in self.data]
        return "%s {%s, data:%s}" % (self._type, self.reason, hexstr)


class MAVLink_unknown(MAVLink_message):
    """
    a message that we don't have in the XML used when built
    """

    def __init__(self, msgid: int, data: bytes) -> None:
        MAVLink_message.__init__(self, MAVLINK_MSG_ID_UNKNOWN, "UNKNOWN_%u" % msgid)
        self._fieldnames = ["data"]
        self.data = data
        self._msgbuf = bytearray(data)
        self._instance_field = None

    def __str__(self) -> str:
        """Override the __str__ function from MAVLink_messages because non-printable characters are common."""
        hexstr = ["{:x}".format(i) for i in self.data]
        return "%s {data:%s}" % (self._type, hexstr)


class MAVLinkSigning(object):
    """MAVLink signing state class"""

    def __init__(self) -> None:
        self.secret_key: Optional[bytes] = None
        self.timestamp = 0
        self.link_id = 0
        self.sign_outgoing = False
        self.allow_unsigned_callback: Optional[Callable[["MAVLink", int], bool]] = None
        self.stream_timestamps: Dict[Tuple[int, int, int], int] = {}
        self.sig_count = 0
        self.badsig_count = 0
        self.goodsig_count = 0
        self.unsigned_count = 0
        self.reject_count = 0


MAVLinkV1Header = Tuple[bytes, int, int, int, int, int]
MAVLinkV2Header = Tuple[bytes, int, int, int, int, int, int, int, int]

class MAVLink(object):
    """MAVLink protocol handling class"""

    def __init__(self, file: Any, srcSystem: int = 0, srcComponent: int = 0, use_native: bool = False) -> None:
        self.seq = 0
        self.file = file
        self.srcSystem = srcSystem
        self.srcComponent = srcComponent
        self.callback: Optional[Callable[..., None]] = None
        self.callback_args: Optional[Iterable[Any]] = None
        self.callback_kwargs: Optional[Mapping[str, Any]] = None
        self.send_callback: Optional[Callable[..., None]] = None
        self.send_callback_args: Optional[Iterable[Any]] = None
        self.send_callback_kwargs: Optional[Mapping[str, Any]] = None
        self.buf = bytearray()
        self.buf_index = 0
        self.expected_length = HEADER_LEN_V1 + 2
        self.have_prefix_error = False
        self.robust_parsing = False
        self.protocol_marker = 253
        self.little_endian = True
        self.crc_extra = True
        self.sort_fields = True
        self.total_packets_sent = 0
        self.total_bytes_sent = 0
        self.total_packets_received = 0
        self.total_bytes_received = 0
        self.total_receive_errors = 0
        self.startup_time = time.time()
        self.signing = MAVLinkSigning()
        self.mav20_unpacker = struct.Struct("<cBBBBBBHB")
        self.mav10_unpacker = struct.Struct("<cBBBBB")
        self.mav20_h3_unpacker = struct.Struct("BBB")
        self.mav_csum_unpacker = struct.Struct("<H")
        self.mav_sign_unpacker = struct.Struct("<IH")

    def set_callback(self, callback: Callable[..., None], *args: Any, **kwargs: Any) -> None:
        self.callback = callback
        self.callback_args = args
        self.callback_kwargs = kwargs

    def set_send_callback(self, callback: Callable[..., None], *args: Any, **kwargs: Any) -> None:
        self.send_callback = callback
        self.send_callback_args = args
        self.send_callback_kwargs = kwargs

    def send(self, mavmsg: MAVLink_message, force_mavlink1: bool = False) -> None:
        """send a MAVLink message"""
        buf = mavmsg.pack(self, force_mavlink1=force_mavlink1)
        self.file.write(buf)
        self.seq = (self.seq + 1) % 256
        self.total_packets_sent += 1
        self.total_bytes_sent += len(buf)
        if self.send_callback is not None and self.send_callback_args is not None and self.send_callback_kwargs is not None:
            self.send_callback(mavmsg, *self.send_callback_args, **self.send_callback_kwargs)

    def buf_len(self) -> int:
        return len(self.buf) - self.buf_index

    def bytes_needed(self) -> int:
        """return number of bytes needed for next parsing stage"""
        ret = self.expected_length - self.buf_len()

        if ret <= 0:
            return 1
        return ret

    def __callbacks(self, msg: MAVLink_message) -> None:
        """this method exists only to make profiling results easier to read"""
        if self.callback is not None and self.callback_args is not None and self.callback_kwargs is not None:
            self.callback(msg, *self.callback_args, **self.callback_kwargs)

    def parse_char(self, c: Sequence[int]) -> Optional[MAVLink_message]:
        """input some data bytes, possibly returning a new message"""
        self.buf.extend(c)

        self.total_bytes_received += len(c)

        m = self.__parse_char_legacy()

        if m is not None:
            self.total_packets_received += 1
            self.__callbacks(m)
        else:
            # XXX The idea here is if we've read something and there's nothing left in
            # the buffer, reset it to 0 which frees the memory
            if self.buf_len() == 0 and self.buf_index != 0:
                self.buf = bytearray()
                self.buf_index = 0

        return m

    def __parse_char_legacy(self) -> Optional[MAVLink_message]:
        """input some data bytes, possibly returning a new message"""
        header_len = HEADER_LEN_V1
        if self.buf_len() >= 1 and self.buf[self.buf_index] == PROTOCOL_MARKER_V2:
            header_len = HEADER_LEN_V2

        m: Optional[MAVLink_message] = None
        if self.buf_len() >= 1 and self.buf[self.buf_index] != PROTOCOL_MARKER_V1 and self.buf[self.buf_index] != PROTOCOL_MARKER_V2:
            magic = self.buf[self.buf_index]
            self.buf_index += 1
            if self.robust_parsing:
                invalid_prefix_start = self.buf_index - 1
                while self.buf_len() >= 1 and self.buf[self.buf_index] != PROTOCOL_MARKER_V1 and self.buf[self.buf_index] != PROTOCOL_MARKER_V2:
                    self.buf_index += 1
                m = MAVLink_bad_data(self.buf[invalid_prefix_start : self.buf_index], "Bad prefix")
                self.expected_length = header_len + 2
                self.total_receive_errors += 1
                return m
            if self.have_prefix_error:
                return None
            self.have_prefix_error = True
            self.total_receive_errors += 1
            raise MAVError("invalid MAVLink prefix '%s'" % magic)
        self.have_prefix_error = False
        if self.buf_len() >= 3:
            sbuf = self.buf[self.buf_index : 3 + self.buf_index]
            unpacked_h3: Tuple[int, int, int] = self.mav20_h3_unpacker.unpack(sbuf)
            magic, self.expected_length, incompat_flags = unpacked_h3
            if magic == PROTOCOL_MARKER_V2 and (incompat_flags & MAVLINK_IFLAG_SIGNED):
                self.expected_length += MAVLINK_SIGNATURE_BLOCK_LEN
            self.expected_length += header_len + 2
        if self.expected_length >= (header_len + 2) and self.buf_len() >= self.expected_length:
            mbuf = self.buf[self.buf_index : self.buf_index + self.expected_length]
            self.buf_index += self.expected_length
            self.expected_length = header_len + 2
            if self.robust_parsing:
                try:
                    if magic == PROTOCOL_MARKER_V2 and (incompat_flags & ~MAVLINK_IFLAG_SIGNED) != 0:
                        raise MAVError("invalid incompat_flags 0x%x 0x%x %u" % (incompat_flags, magic, self.expected_length))
                    m = self.decode(mbuf)
                except MAVError as reason:
                    m = MAVLink_bad_data(mbuf, reason.message)
                    self.total_receive_errors += 1
            else:
                if magic == PROTOCOL_MARKER_V2 and (incompat_flags & ~MAVLINK_IFLAG_SIGNED) != 0:
                    raise MAVError("invalid incompat_flags 0x%x 0x%x %u" % (incompat_flags, magic, self.expected_length))
                m = self.decode(mbuf)
            return m
        return None

    def parse_buffer(self, s: Sequence[int]) -> Optional[List[MAVLink_message]]:
        """input some data bytes, possibly returning a list of new messages"""
        m = self.parse_char(s)
        if m is None:
            return None
        ret = [m]
        while True:
            m = self.parse_char(b"")
            if m is None:
                return ret
            ret.append(m)

    def check_signature(self, msgbuf: bytearray, srcSystem: int, srcComponent: int) -> bool:
        """check signature on incoming message"""
        assert self.signing.secret_key is not None

        timestamp_buf = msgbuf[-12:-6]
        link_id = msgbuf[-13]
        tbytes: Tuple[int, int] = self.mav_sign_unpacker.unpack(timestamp_buf)
        tlow, thigh = tbytes
        timestamp = tlow + (thigh << 32)

        # see if the timestamp is acceptable
        stream_key = (link_id, srcSystem, srcComponent)
        if stream_key in self.signing.stream_timestamps:
            if timestamp <= self.signing.stream_timestamps[stream_key]:
                # reject old timestamp
                logger.info("old timestamp")
                return False
        else:
            # a new stream has appeared. Accept the timestamp if it is at most
            # one minute behind our current timestamp
            if timestamp + 6000 * 1000 < self.signing.timestamp:
                logger.info("bad new stream %s %s", timestamp / (100.0 * 1000 * 60 * 60 * 24 * 365), self.signing.timestamp / (100.0 * 1000 * 60 * 60 * 24 * 365))
                return False
            logger.info("new stream")

        # set the streams timestamp so we reject timestamps that go backwards
        self.signing.stream_timestamps[stream_key] = timestamp

        h = hashlib.new("sha256")
        h.update(self.signing.secret_key)
        h.update(msgbuf[:-6])
        sig1 = h.digest()[:6]
        sig2 = msgbuf[-6:]
        if sig1 != sig2:
            logger.info("sig mismatch")
            return False

        # the timestamp we next send with is the max of the received timestamp and
        # our current timestamp
        self.signing.timestamp = max(self.signing.timestamp, timestamp)
        return True

    def decode(self, msgbuf: bytearray) -> MAVLink_message:
        """decode a buffer as a MAVLink message"""
        # decode the header
        if msgbuf[0] != PROTOCOL_MARKER_V1:
            headerlen = 10
            try:
                header_v2: MAVLinkV2Header = self.mav20_unpacker.unpack(msgbuf[:headerlen])
            except struct.error as emsg:
                raise MAVError("Unable to unpack MAVLink header: %s" % emsg)
            magic, mlen, incompat_flags, compat_flags, seq, srcSystem, srcComponent, msgIdlow, msgIdhigh = header_v2
            msgId = msgIdlow | (msgIdhigh << 16)
        else:
            headerlen = 6
            try:
                header_v1: MAVLinkV1Header = self.mav10_unpacker.unpack(msgbuf[:headerlen])
            except struct.error as emsg:
                raise MAVError("Unable to unpack MAVLink header: %s" % emsg)
            magic, mlen, seq, srcSystem, srcComponent, msgId = header_v1
            incompat_flags = 0
            compat_flags = 0
        mapkey = msgId
        if (incompat_flags & MAVLINK_IFLAG_SIGNED) != 0:
            signature_len = MAVLINK_SIGNATURE_BLOCK_LEN
        else:
            signature_len = 0

        if ord(magic) != PROTOCOL_MARKER_V1 and ord(magic) != PROTOCOL_MARKER_V2:
            raise MAVError("invalid MAVLink prefix '{}'".format(hex(ord(magic))))
        if mlen != len(msgbuf) - (headerlen + 2 + signature_len):
            raise MAVError("invalid MAVLink message length. Got %u expected %u, msgId=%u headerlen=%u" % (len(msgbuf) - (headerlen + 2 + signature_len), mlen, msgId, headerlen))

        if mapkey not in mavlink_map:
            return MAVLink_unknown(msgId, msgbuf)

        # decode the payload
        msgtype = mavlink_map[mapkey]
        order_map = msgtype.orders
        len_map = msgtype.lengths
        crc_extra = msgtype.crc_extra

        # decode the checksum
        try:
            crc: int = self.mav_csum_unpacker.unpack(msgbuf[-(2 + signature_len) :][:2])[0]
        except struct.error as emsg:
            raise MAVError("Unable to unpack MAVLink CRC: %s" % emsg)
        crcbuf = msgbuf[1 : -(2 + signature_len)]
        if True:
            # using CRC extra
            crcbuf.append(crc_extra)
        crc2 = x25crc(crcbuf)
        if crc != crc2.crc and not MAVLINK_IGNORE_CRC:
            raise MAVError("invalid MAVLink CRC in msgID %u 0x%04x should be 0x%04x" % (msgId, crc, crc2.crc))

        sig_ok = False
        if signature_len == MAVLINK_SIGNATURE_BLOCK_LEN:
            self.signing.sig_count += 1
        if self.signing.secret_key is not None:
            accept_signature = False
            if signature_len == MAVLINK_SIGNATURE_BLOCK_LEN:
                sig_ok = self.check_signature(msgbuf, srcSystem, srcComponent)
                accept_signature = sig_ok
                if sig_ok:
                    self.signing.goodsig_count += 1
                else:
                    self.signing.badsig_count += 1
                if not accept_signature and self.signing.allow_unsigned_callback is not None:
                    accept_signature = self.signing.allow_unsigned_callback(self, msgId)
                    if accept_signature:
                        self.signing.unsigned_count += 1
                    else:
                        self.signing.reject_count += 1
            elif self.signing.allow_unsigned_callback is not None:
                accept_signature = self.signing.allow_unsigned_callback(self, msgId)
                if accept_signature:
                    self.signing.unsigned_count += 1
                else:
                    self.signing.reject_count += 1
            if not accept_signature:
                raise MAVError("Invalid signature")

        csize = msgtype.unpacker.size
        mbuf = msgbuf[headerlen : -(2 + signature_len)]
        if len(mbuf) < csize:
            # zero pad to give right size
            mbuf.extend([0] * (csize - len(mbuf)))
        if len(mbuf) < csize:
            raise MAVError("Bad message of type %s length %u needs %s" % (msgtype, len(mbuf), csize))
        mbuf = mbuf[:csize]
        try:
            t: Tuple[Union[bytes, int, float], ...] = msgtype.unpacker.unpack(mbuf)
        except struct.error as emsg:
            raise MAVError("Unable to unpack MAVLink payload type=%s payloadLength=%u: %s" % (msgtype, len(mbuf), emsg))

        tlist: List[Union[bytes, float, int, Sequence[Union[bytes, float, int]]]] = list(t)
        # handle sorted fields
        if True:
            if sum(len_map) == len(len_map):
                # message has no arrays in it
                for i in range(0, len(tlist)):
                    tlist[i] = t[order_map[i]]
            else:
                # message has some arrays
                tlist = []
                for i in range(0, len(order_map)):
                    order = order_map[i]
                    L = len_map[order]
                    tip = sum(len_map[:order])
                    field = t[tip]
                    if L == 1 or isinstance(field, bytes):
                        tlist.append(field)
                    else:
                        tlist.append(list(t[tip : (tip + L)]))

        # terminate any strings
        for i, elem in enumerate(tlist):
            if isinstance(elem, bytes):
                tlist[i] = elem.rstrip(b"\x00")

        # construct the message object
        try:
            # Note that initializers don't follow the Liskov Substitution Principle
            # therefore it can't be typechecked
            m = msgtype(*tlist)  # type: ignore
        except Exception as emsg:
            raise MAVError("Unable to instantiate MAVLink message of type %s : %s" % (msgtype, emsg))
        m._signed = sig_ok
        if m._signed:
            m._link_id = msgbuf[-13]
        m._msgbuf = msgbuf
        m._payload = msgbuf[6 : -(2 + signature_len)]
        m._crc = crc
        m._header = MAVLink_header(msgId, incompat_flags, compat_flags, mlen, seq, srcSystem, srcComponent)
        return m

    def ihm_board_state_encode(self, buttons: int, encoder0_direction: int, encoder1_direction: int, encoder2_direction: int, rotation: int, charging: int, batt_voltage: int, analog_in: Sequence[int], time_statistics: int, time_counter: int) -> MAVLink_ihm_board_state_message:
        """
        Periodic/on-change snapshot of the board's user-input state, analog
        inputs, and loop-timing debug info. Board -> PC, telemetry.
        Field widths are intentionally not bit-packed across byte
        boundaries         (e.g. each encoder gets its own byte rather
        than 3 encoders sharing         9 bits): with
        MAVLINK_MAX_PAYLOAD_LEN raised to 64 for future
        headroom, the few bytes saved by tight packing weren't worth
        the         hand-rolled bit-shift/mask code on both the
        firmware and PC sides.         This message is 19 bytes either
        way, well under the cap.

        buttons                   : Bitmask of the 7 push-buttons, 1 = pressed. Bits 0-3: btn0-btn3.
        Bits 4-6: encoder0/1/2 push-buttons. Bit 7 unused (BinaryInput's own
        buildButtonMap() hardcodes this bit as a sentinel; we don't carry
        that here, it's just left 0). (type:uint8_t)
        encoder0_direction        : Encoder 0 movement since last sample. (type:uint8_t, values:IHM_ENCODER_DIRECTION)
        encoder1_direction        : Encoder 1 movement since last sample. (type:uint8_t, values:IHM_ENCODER_DIRECTION)
        encoder2_direction        : Encoder 2 movement since last sample. (type:uint8_t, values:IHM_ENCODER_DIRECTION)
        rotation                  : House-keeping orientation/rotation sensor. 0/1. (type:uint8_t)
        charging                  : House-keeping charging-status input. 0/1. (type:uint8_t)
        batt_voltage              : Raw battery-voltage ADC reading, 10-bit (0-1023) -- ATmega2560's
        built-in ADC, no external converter on this input. (type:uint16_t)
        analog_in                 : Raw an0_in..an3_in ADC readings, 10-bit each (0-1023). (type:uint16_t)
        time_statistics           : Raw value of main.cpp's volatile timeStatistics accumulator
        (accumulated TCNT2 ticks). Send as-is, unaveraged -- pair with
        time_counter below to compute the same ratio the firmware's own
        status bar does. (type:uint16_t)
        time_counter              : Raw value of main.cpp's volatile timeCounter (number of ticks
        accumulated into time_statistics so far, resets at 100). (type:uint8_t)

        """
        return MAVLink_ihm_board_state_message(buttons, encoder0_direction, encoder1_direction, encoder2_direction, rotation, charging, batt_voltage, analog_in, time_statistics, time_counter)

    def ihm_board_state_send(self, buttons: int, encoder0_direction: int, encoder1_direction: int, encoder2_direction: int, rotation: int, charging: int, batt_voltage: int, analog_in: Sequence[int], time_statistics: int, time_counter: int, force_mavlink1: bool = False) -> None:
        """
        Periodic/on-change snapshot of the board's user-input state, analog
        inputs, and loop-timing debug info. Board -> PC, telemetry.
        Field widths are intentionally not bit-packed across byte
        boundaries         (e.g. each encoder gets its own byte rather
        than 3 encoders sharing         9 bits): with
        MAVLINK_MAX_PAYLOAD_LEN raised to 64 for future
        headroom, the few bytes saved by tight packing weren't worth
        the         hand-rolled bit-shift/mask code on both the
        firmware and PC sides.         This message is 19 bytes either
        way, well under the cap.

        buttons                   : Bitmask of the 7 push-buttons, 1 = pressed. Bits 0-3: btn0-btn3.
        Bits 4-6: encoder0/1/2 push-buttons. Bit 7 unused (BinaryInput's own
        buildButtonMap() hardcodes this bit as a sentinel; we don't carry
        that here, it's just left 0). (type:uint8_t)
        encoder0_direction        : Encoder 0 movement since last sample. (type:uint8_t, values:IHM_ENCODER_DIRECTION)
        encoder1_direction        : Encoder 1 movement since last sample. (type:uint8_t, values:IHM_ENCODER_DIRECTION)
        encoder2_direction        : Encoder 2 movement since last sample. (type:uint8_t, values:IHM_ENCODER_DIRECTION)
        rotation                  : House-keeping orientation/rotation sensor. 0/1. (type:uint8_t)
        charging                  : House-keeping charging-status input. 0/1. (type:uint8_t)
        batt_voltage              : Raw battery-voltage ADC reading, 10-bit (0-1023) -- ATmega2560's
        built-in ADC, no external converter on this input. (type:uint16_t)
        analog_in                 : Raw an0_in..an3_in ADC readings, 10-bit each (0-1023). (type:uint16_t)
        time_statistics           : Raw value of main.cpp's volatile timeStatistics accumulator
        (accumulated TCNT2 ticks). Send as-is, unaveraged -- pair with
        time_counter below to compute the same ratio the firmware's own
        status bar does. (type:uint16_t)
        time_counter              : Raw value of main.cpp's volatile timeCounter (number of ticks
        accumulated into time_statistics so far, resets at 100). (type:uint8_t)

        """
        self.send(self.ihm_board_state_encode(buttons, encoder0_direction, encoder1_direction, encoder2_direction, rotation, charging, batt_voltage, analog_in, time_statistics, time_counter), force_mavlink1=force_mavlink1)

    def can_signal_config_encode(self, bus_id: int, can_id: int, extended_id: int, dlc: int, data: Sequence[int], period_ms: int, repeat_count: int, enable: int) -> MAVLink_can_signal_config_message:
        """
        Configure/start/stop a generated signal on one of the board's 2 CAN
        buses. One active signal per bus -- sending a new config for a
        bus_id replaces whatever was previously configured there. The
        board         transmits exactly the given bytes on a schedule;
        no waveform math         happens on-board. PC -> board,
        command.

        bus_id                    : Target CAN bus: 0 or 1. (type:uint8_t)
        can_id                    : CAN identifier (standard or extended, see extended_id). (type:uint32_t)
        extended_id               : 0 = standard 11-bit ID, 1 = extended 29-bit ID. (type:uint8_t)
        dlc                       : Data length, 0-8 (classic CAN). (type:uint8_t)
        data                      : Frame payload bytes; only the first dlc bytes are used. (type:uint8_t)
        period_ms                 : Repeat interval in ms. 0 = send once (one-shot). (type:uint16_t)
        repeat_count              : Number of times to send. 0 = repeat until disabled. (type:uint16_t)
        enable                    : 1 = start/keep running, 0 = stop. Resend with 0 to stop a running generator. (type:uint8_t)

        """
        return MAVLink_can_signal_config_message(bus_id, can_id, extended_id, dlc, data, period_ms, repeat_count, enable)

    def can_signal_config_send(self, bus_id: int, can_id: int, extended_id: int, dlc: int, data: Sequence[int], period_ms: int, repeat_count: int, enable: int, force_mavlink1: bool = False) -> None:
        """
        Configure/start/stop a generated signal on one of the board's 2 CAN
        buses. One active signal per bus -- sending a new config for a
        bus_id replaces whatever was previously configured there. The
        board         transmits exactly the given bytes on a schedule;
        no waveform math         happens on-board. PC -> board,
        command.

        bus_id                    : Target CAN bus: 0 or 1. (type:uint8_t)
        can_id                    : CAN identifier (standard or extended, see extended_id). (type:uint32_t)
        extended_id               : 0 = standard 11-bit ID, 1 = extended 29-bit ID. (type:uint8_t)
        dlc                       : Data length, 0-8 (classic CAN). (type:uint8_t)
        data                      : Frame payload bytes; only the first dlc bytes are used. (type:uint8_t)
        period_ms                 : Repeat interval in ms. 0 = send once (one-shot). (type:uint16_t)
        repeat_count              : Number of times to send. 0 = repeat until disabled. (type:uint16_t)
        enable                    : 1 = start/keep running, 0 = stop. Resend with 0 to stop a running generator. (type:uint8_t)

        """
        self.send(self.can_signal_config_encode(bus_id, can_id, extended_id, dlc, data, period_ms, repeat_count, enable), force_mavlink1=force_mavlink1)

    def rs485_signal_config_encode(self, length: int, data: Sequence[int], period_ms: int, repeat_count: int, enable: int) -> MAVLink_rs485_signal_config_message:
        """
        Configure/start/stop a generated signal on the board's RS-485
        connection. One active signal at a time -- a new config
        replaces         whatever was previously running. Raw byte
        transmission, no framing         imposed (no protocol defined
        over this link yet). PC -> board,         command.

        length                    : Valid byte count in data, 0-32. (type:uint8_t)
        data                      : Raw payload bytes; only the first length bytes are used. (type:uint8_t)
        period_ms                 : Repeat interval in ms. 0 = send once (one-shot). (type:uint16_t)
        repeat_count              : Number of times to send. 0 = repeat until disabled. (type:uint16_t)
        enable                    : 1 = start/keep running, 0 = stop. Resend with 0 to stop a running generator. (type:uint8_t)

        """
        return MAVLink_rs485_signal_config_message(length, data, period_ms, repeat_count, enable)

    def rs485_signal_config_send(self, length: int, data: Sequence[int], period_ms: int, repeat_count: int, enable: int, force_mavlink1: bool = False) -> None:
        """
        Configure/start/stop a generated signal on the board's RS-485
        connection. One active signal at a time -- a new config
        replaces         whatever was previously running. Raw byte
        transmission, no framing         imposed (no protocol defined
        over this link yet). PC -> board,         command.

        length                    : Valid byte count in data, 0-32. (type:uint8_t)
        data                      : Raw payload bytes; only the first length bytes are used. (type:uint8_t)
        period_ms                 : Repeat interval in ms. 0 = send once (one-shot). (type:uint16_t)
        repeat_count              : Number of times to send. 0 = repeat until disabled. (type:uint16_t)
        enable                    : 1 = start/keep running, 0 = stop. Resend with 0 to stop a running generator. (type:uint8_t)

        """
        self.send(self.rs485_signal_config_encode(length, data, period_ms, repeat_count, enable), force_mavlink1=force_mavlink1)

    def pwm_channel_config_encode(self, channel: int, f_selector: int, frequency: int, out1_enabled: int, out1_inverting: int, out1_duty_percent: int, out2_enabled: int, out2_inverting: int, out2_duty_percent: int, out3_enabled: int, out3_inverting: int, out3_duty_percent: int) -> MAVLink_pwm_channel_config_message:
        """
        Configure one of the board's 4 PWM channels. PC -> board, command.
        The board applies it to the timer registers immediately; there
        is         no ack. Sending a new config for a channel replaces
        its previous         one (last writer wins, including against
        the on-screen PWM tab,         which drives the same
        registers).          One message shape covers both channel
        kinds (see         IHM/lib/MultiOutput/src/PWM.h):           *
        channels 0 and 1 are "simplex" -- a single output (OC3A /
        OC5A). Only out1_* is used; out2_* and out3_* are ignored.
        * channels 2 and 3 are "complex" -- three independent outputs
        A/B/C (OC1A/B/C, OC4A/B/C). out1_/out2_/out3_ map to A/B/C.
        Same "not bit-packed across byte boundaries" convention as the
        other messages here -- each flag gets its own byte. 13 bytes,
        well under the 64-byte cap.

        channel                   : Target PWM channel, 0-3. Out-of-range configs are dropped by the board. (type:uint8_t)
        f_selector                : Frequency selector for the whole channel. (type:uint8_t, values:PWM_FREQUENCY)
        frequency                 : Raw ICRn TOP (timer period). Only read when f_selector ==
        PWM_FREQUENCY_VARIABLE; ignored for every fixed selector. (type:uint16_t)
        out1_enabled              : Output A: 1 = drive the pin, 0 = disconnect it. (type:uint8_t)
        out1_inverting            : Output A: 0 = non-inverting (high from period start), 1 = inverting. (type:uint8_t)
        out1_duty_percent         : Output A duty cycle, 0-100. Scaled against the selector's resolution on-board. (type:uint8_t)
        out2_enabled              : Output B enable. Ignored for channels 0 and 1. (type:uint8_t)
        out2_inverting            : Output B edge polarity. Ignored for channels 0 and 1. (type:uint8_t)
        out2_duty_percent         : Output B duty cycle, 0-100. Ignored for channels 0 and 1. (type:uint8_t)
        out3_enabled              : Output C enable. Ignored for channels 0 and 1. (type:uint8_t)
        out3_inverting            : Output C edge polarity. Ignored for channels 0 and 1. (type:uint8_t)
        out3_duty_percent         : Output C duty cycle, 0-100. Ignored for channels 0 and 1. (type:uint8_t)

        """
        return MAVLink_pwm_channel_config_message(channel, f_selector, frequency, out1_enabled, out1_inverting, out1_duty_percent, out2_enabled, out2_inverting, out2_duty_percent, out3_enabled, out3_inverting, out3_duty_percent)

    def pwm_channel_config_send(self, channel: int, f_selector: int, frequency: int, out1_enabled: int, out1_inverting: int, out1_duty_percent: int, out2_enabled: int, out2_inverting: int, out2_duty_percent: int, out3_enabled: int, out3_inverting: int, out3_duty_percent: int, force_mavlink1: bool = False) -> None:
        """
        Configure one of the board's 4 PWM channels. PC -> board, command.
        The board applies it to the timer registers immediately; there
        is         no ack. Sending a new config for a channel replaces
        its previous         one (last writer wins, including against
        the on-screen PWM tab,         which drives the same
        registers).          One message shape covers both channel
        kinds (see         IHM/lib/MultiOutput/src/PWM.h):           *
        channels 0 and 1 are "simplex" -- a single output (OC3A /
        OC5A). Only out1_* is used; out2_* and out3_* are ignored.
        * channels 2 and 3 are "complex" -- three independent outputs
        A/B/C (OC1A/B/C, OC4A/B/C). out1_/out2_/out3_ map to A/B/C.
        Same "not bit-packed across byte boundaries" convention as the
        other messages here -- each flag gets its own byte. 13 bytes,
        well under the 64-byte cap.

        channel                   : Target PWM channel, 0-3. Out-of-range configs are dropped by the board. (type:uint8_t)
        f_selector                : Frequency selector for the whole channel. (type:uint8_t, values:PWM_FREQUENCY)
        frequency                 : Raw ICRn TOP (timer period). Only read when f_selector ==
        PWM_FREQUENCY_VARIABLE; ignored for every fixed selector. (type:uint16_t)
        out1_enabled              : Output A: 1 = drive the pin, 0 = disconnect it. (type:uint8_t)
        out1_inverting            : Output A: 0 = non-inverting (high from period start), 1 = inverting. (type:uint8_t)
        out1_duty_percent         : Output A duty cycle, 0-100. Scaled against the selector's resolution on-board. (type:uint8_t)
        out2_enabled              : Output B enable. Ignored for channels 0 and 1. (type:uint8_t)
        out2_inverting            : Output B edge polarity. Ignored for channels 0 and 1. (type:uint8_t)
        out2_duty_percent         : Output B duty cycle, 0-100. Ignored for channels 0 and 1. (type:uint8_t)
        out3_enabled              : Output C enable. Ignored for channels 0 and 1. (type:uint8_t)
        out3_inverting            : Output C edge polarity. Ignored for channels 0 and 1. (type:uint8_t)
        out3_duty_percent         : Output C duty cycle, 0-100. Ignored for channels 0 and 1. (type:uint8_t)

        """
        self.send(self.pwm_channel_config_encode(channel, f_selector, frequency, out1_enabled, out1_inverting, out1_duty_percent, out2_enabled, out2_inverting, out2_duty_percent, out3_enabled, out3_inverting, out3_duty_percent), force_mavlink1=force_mavlink1)

    def ihm_relay_state_encode(self, relays: int) -> MAVLink_ihm_relay_state_message:
        """
        Periodic snapshot of all 8 relay outputs. Board -> PC, telemetry,
        read-only -- there is no PC -> board relay command yet (relays
        are         only toggled locally, by the physical buttons or
        the on-screen         Relay tab). Mirrors main.cpp's
        relayState[NUMBER_OF_RELAYS] the         same way
        IHM_BOARD_STATE.buttons mirrors the button bitmap.

        relays                    : Bitmask, bit i = relay i (0-7), 1 = on. (type:uint8_t)

        """
        return MAVLink_ihm_relay_state_message(relays)

    def ihm_relay_state_send(self, relays: int, force_mavlink1: bool = False) -> None:
        """
        Periodic snapshot of all 8 relay outputs. Board -> PC, telemetry,
        read-only -- there is no PC -> board relay command yet (relays
        are         only toggled locally, by the physical buttons or
        the on-screen         Relay tab). Mirrors main.cpp's
        relayState[NUMBER_OF_RELAYS] the         same way
        IHM_BOARD_STATE.buttons mirrors the button bitmap.

        relays                    : Bitmask, bit i = relay i (0-7), 1 = on. (type:uint8_t)

        """
        self.send(self.ihm_relay_state_encode(relays), force_mavlink1=force_mavlink1)

    def ihm_simulate_encoder_encode(self, encoder: int, direction: int) -> MAVLink_ihm_simulate_encoder_message:
        """
        PC injects one simulated rotation step on the given encoder. The
        board applies it only if that encoder's real hardware read was
        idle (not_supported) on the same superloop pass -- real input
        always wins, no fight between the two sources. Consumed
        exactly         once, mirroring the real encoder's own edge-
        triggered/consumed-         on-read semantics
        (RotaryEncoder.h). No ack. PC -> board, command.

        encoder                   : Target encoder, 0-2. Out-of-range is dropped by the board. (type:uint8_t)
        direction                 : CW or CCW; NOT_SUPPORTED is a no-op. (type:uint8_t, values:IHM_ENCODER_DIRECTION)

        """
        return MAVLink_ihm_simulate_encoder_message(encoder, direction)

    def ihm_simulate_encoder_send(self, encoder: int, direction: int, force_mavlink1: bool = False) -> None:
        """
        PC injects one simulated rotation step on the given encoder. The
        board applies it only if that encoder's real hardware read was
        idle (not_supported) on the same superloop pass -- real input
        always wins, no fight between the two sources. Consumed
        exactly         once, mirroring the real encoder's own edge-
        triggered/consumed-         on-read semantics
        (RotaryEncoder.h). No ack. PC -> board, command.

        encoder                   : Target encoder, 0-2. Out-of-range is dropped by the board. (type:uint8_t)
        direction                 : CW or CCW; NOT_SUPPORTED is a no-op. (type:uint8_t, values:IHM_ENCODER_DIRECTION)

        """
        self.send(self.ihm_simulate_encoder_encode(encoder, direction), force_mavlink1=force_mavlink1)
