#ifndef JANUS_GEN_ACTIONS_H
#define JANUS_GEN_ACTIONS_H

typedef enum {
    JANUS_ACTION_NONE,
    JANUS_ACTION_TOGGLE_RELAY_0,
    JANUS_ACTION_TOGGLE_RELAY_1,
    JANUS_ACTION_TOGGLE_RELAY_2,
    JANUS_ACTION_TOGGLE_RELAY_3,
    JANUS_ACTION_TOGGLE_RELAY_4,
    JANUS_ACTION_TOGGLE_RELAY_5,
    JANUS_ACTION_TOGGLE_RELAY_6,
    JANUS_ACTION_TOGGLE_RELAY_7
} janus_action_t;

void janus_handle_action(janus_action_t action);

#endif  /* JANUS_GEN_ACTIONS_H */
