#ifndef JANUS_GEN_ACTIONS_H
#define JANUS_GEN_ACTIONS_H

typedef enum {
    JANUS_ACTION_NONE,
    JANUS_ACTION_TOGGLE_PWM_CH0_ENABLED,
    JANUS_ACTION_TOGGLE_PWM_CH0_INVERTING,
    JANUS_ACTION_TOGGLE_PWM_CH1_ENABLED,
    JANUS_ACTION_TOGGLE_PWM_CH1_INVERTING,
    JANUS_ACTION_TOGGLE_PWM_CH2_A_ENABLED,
    JANUS_ACTION_TOGGLE_PWM_CH2_B_ENABLED,
    JANUS_ACTION_TOGGLE_PWM_CH2_C_ENABLED,
    JANUS_ACTION_TOGGLE_PWM_CH3_A_ENABLED,
    JANUS_ACTION_TOGGLE_PWM_CH3_B_ENABLED,
    JANUS_ACTION_TOGGLE_PWM_CH3_C_ENABLED,
    JANUS_ACTION_TOGGLE_RELAY_0,
    JANUS_ACTION_TOGGLE_RELAY_1,
    JANUS_ACTION_TOGGLE_RELAY_2,
    JANUS_ACTION_TOGGLE_RELAY_3,
    JANUS_ACTION_TOGGLE_RELAY_4,
    JANUS_ACTION_TOGGLE_RELAY_5,
    JANUS_ACTION_TOGGLE_RELAY_6,
    JANUS_ACTION_TOGGLE_RELAY_7
} janus_action_t;

void janus_handle_action(janus_action_t action);

#endif  /* JANUS_GEN_ACTIONS_H */
