#ifndef JANUS_GEN_DISPLAY_CONFIG_H
#define JANUS_GEN_DISPLAY_CONFIG_H

#define JANUS_DISPLAY_WIDTH 320
#define JANUS_DISPLAY_HEIGHT 480

#define JANUS_DISPLAY_COLOR_MONO 0
#define JANUS_DISPLAY_COLOR_GRAY 1
#define JANUS_DISPLAY_COLOR_RGB565 2
#define JANUS_DISPLAY_COLOR JANUS_DISPLAY_COLOR_RGB565

#define JANUS_DISPLAY_BUS_SPI 0
#define JANUS_DISPLAY_BUS_I2C 1
#define JANUS_DISPLAY_BUS_PARALLEL 2
#define JANUS_DISPLAY_BUS JANUS_DISPLAY_BUS_PARALLEL

#define JANUS_DISPLAY_CONTROLLER_ST7789 0
#define JANUS_DISPLAY_CONTROLLER_ST7789V 1
#define JANUS_DISPLAY_CONTROLLER_ILI9341 2
#define JANUS_DISPLAY_CONTROLLER_ILI9341V 3
#define JANUS_DISPLAY_CONTROLLER_HX8357 4
#define JANUS_DISPLAY_CONTROLLER_GC9A01 5
#define JANUS_DISPLAY_CONTROLLER_SSD1306 6
#define JANUS_DISPLAY_CONTROLLER_SH1106 7
#define JANUS_DISPLAY_CONTROLLER_IL3820 8
#define JANUS_DISPLAY_CONTROLLER_IL0373 9

#define JANUS_DISPLAY_RENDER_MODE_BLOCKING 0
#define JANUS_DISPLAY_RENDER_MODE_NON_BLOCKING 1
#define JANUS_DISPLAY_RENDER_MODE JANUS_DISPLAY_RENDER_MODE_BLOCKING

#endif  /* JANUS_GEN_DISPLAY_CONFIG_H */
